### ISSUE TITLE
CR-272 Perk Entitlement and Policy Change

### ISSUE THREAD

**Issue by 0340LalitGupta** [Isgec/WebTA1#11]
It has been decided to restructure payment of some perks. The brief changes are: 1.	Restarting perks like Outfit/Uniform and books & periodicals. 2.	Provide driver salary from Senior Manager level in place of Vehicle maintenance. 3.	Changes in medical reimbursement. These changes are to be affected from 1st October 2018.  We request you to arrange for making necessary changes in Perks Management System so that we can start revised perks system from this quarter. The detailed changes  can be discussed when we meet for updation in Perks Management System
======================================================
Details As per proposed perks dated 28 Feb 2019
======================================================
Discontinue Medical, if no vehicle.

**Comment by 0340LalitGupta** [comment]
Feedback is awaited from Rawat.

**Comment by hariharan-isgec** [comment]
@0340LalitGupta 
Update Changes done in Master Data to implement above changes
