### ISSUE TITLE
Allow Mr. Khurana to submit more than 3 PERKS claims in a quarter.

### ISSUE THREAD

**Issue by 0340LalitGupta** [Isgec/WebTA1#4]
Allow Mr. Khurana to submit more than 3 PERKS claims in a quarter.

**Comment by hariharan-isgec** [comment]
@0340LalitGupta update delivery plan for this request

**Comment by 0340LalitGupta** [comment]
@hariharan-isgec 
changes required for this done and confirmed by Rawat.

You may close this issue.
