### ISSUE TITLE
Changes in Driver Charges Entitlement

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/WebTA1#6]
![image](https://user-images.githubusercontent.com/43699418/50749756-f94c4480-1266-11e9-9b54-20fb6107b40c.png)
@0340LalitGupta Please take a CR and get it done

**Comment by 0340LalitGupta** [comment]
Driver charges calculation is working fine for old claim as well as for new claim. Confirmed by Rawat.
@hariharan-isgec 
Pl. close this issue.
