### ISSUE TITLE
CR-351 - Implement Modification in TA/DA Rule

### ISSUE THREAD

**Issue by hariharan-isgec** [Isgec/WebTA1#8]
![image](https://user-images.githubusercontent.com/43699418/54069779-781e2780-4280-11e9-9c78-404650bf92b1.png)
![image](https://user-images.githubusercontent.com/43699418/54069784-80766280-4280-11e9-8a2a-80793b54bbf7.png)
![image](https://user-images.githubusercontent.com/43699418/54069789-85d3ad00-4280-11e9-9b3b-a0a58d35bc47.png)
![image](https://user-images.githubusercontent.com/43699418/54069795-8b30f780-4280-11e9-8ea0-71cf2531eb4e.png)

@0340LalitGupta

**Comment by 0340LalitGupta** [comment]
Code Committed New TA Rules, copied on Live for A/c to check.
