### ISSUE TITLE
Supplier GSTIN length check & show CGST/SGST separately

### ISSUE THREAD

**Issue by 0340LalitGupta** [Isgec/WebTA1#9]
1. Supplier GSTIN length should be 15 chars/digits
2. Show SGST and CGST separately in print.

**Comment by 0340LalitGupta** [comment]
1. GSTIN length check of 15 Chars
=====================
![image](https://user-images.githubusercontent.com/37236522/55054630-9197df80-5086-11e9-99fb-f09da83ba3e4.png)


2. SGST, CGST shown separately
=====================
![image](https://user-images.githubusercontent.com/37236522/55054556-54cbe880-5086-11e9-8a0e-84681d09fc6d.png)

**Comment by hariharan-isgec** [comment]
Change approved for Production
